const std = @import("std");
const phx = @import("../../phoenix.zig");
const x11 = phx.x11;

const Self = @This();

/// These keys match the keyboard keys in linux/input-event-codes.h that map to X11 keys.
/// There are more keys defined but we do not currently use them.
const Key = enum(u8) {
    // zig fmt: off
    reserved         = 0,
    esc              = 1,
    num1             = 2,
    num2             = 3,
    num3             = 4,
    num4             = 5,
    num5             = 6,
    num6             = 7,
    num7             = 8,
    num8             = 9,
    num9             = 10,
    num0             = 11,
    minus            = 12,
    equal            = 13,
    backspace        = 14,
    tab              = 15,
    q                = 16,
    w                = 17,
    e                = 18,
    r                = 19,
    t                = 20,
    y                = 21,
    u                = 22,
    i                = 23,
    o                = 24,
    p                = 25,
    leftbrace        = 26,
    rightbrace       = 27,
    enter            = 28,
    leftctrl         = 29,
    a                = 30,
    s                = 31,
    d                = 32,
    f                = 33,
    g                = 34,
    h                = 35,
    j                = 36,
    k                = 37,
    l                = 38,
    semicolon        = 39,
    apostrophe       = 40,
    grave            = 41,
    leftshift        = 42,
    backslash        = 43,
    z                = 44,
    x                = 45,
    c                = 46,
    v                = 47,
    b                = 48,
    n                = 49,
    m                = 50,
    comma            = 51,
    dot              = 52,
    slash            = 53,
    rightshift       = 54,
    kpasterisk       = 55,
    leftalt          = 56,
    space            = 57,
    capslock         = 58,
    f1               = 59,
    f2               = 60,
    f3               = 61,
    f4               = 62,
    f5               = 63,
    f6               = 64,
    f7               = 65,
    f8               = 66,
    f9               = 67,
    f10              = 68,
    numlock          = 69,
    scrolllock       = 70,
    kp7              = 71,
    kp8              = 72,
    kp9              = 73,
    kpminus          = 74,
    kp4              = 75,
    kp5              = 76,
    kp6              = 77,
    kpplus           = 78,
    kp1              = 79,
    kp2              = 80,
    kp3              = 81,
    kp0              = 82,
    kpdot            = 83,
    zenkakuhankaku   = 85,
    key_102nd        = 86,
    f11              = 87,
    f12              = 88,
    ro               = 89,
    katakana         = 90,
    hiragana         = 91,
    henkan           = 92,
    katakanahiragana = 93,
    muhenkan         = 94,
    kpjpcomma        = 95,
    kpenter          = 96,
    rightctrl        = 97,
    kpslash          = 98,
    sysrq            = 99,
    rightalt         = 100,
    linefeed         = 101,
    home             = 102,
    up               = 103,
    pageup           = 104,
    left             = 105,
    right            = 106,
    end              = 107,
    down             = 108,
    pagedown         = 109,
    insert           = 110,
    delete           = 111,
    macro            = 112,
    mute             = 113,
    volumedown       = 114,
    volumeup         = 115,
    power            = 116,                 // SC System Power Down
    kpequal          = 117,
    kpplusminus      = 118,
    pause            = 119,
    scale            = 120,                 // AL Compiz Scale (Expose)
    kpcomma          = 121,
    hangeul          = 122,
    hanja            = 123,
    yen              = 124,
    leftmeta         = 125,
    rightmeta        = 126,
    compose          = 127,
    stop             = 128,                 //  AC Stop
    again            = 129,
    props            = 130,                 //  AC Properties
    undo             = 131,                 //  AC Undo
    front            = 132,
    copy             = 133,                 //  AC Copy
    open             = 134,                 //  AC Open
    paste            = 135,                 //  AC Paste
    find             = 136,                 //  AC Search
    cut              = 137,                 //  AC Cut
    help             = 138,                 //  AL Integrated Help Center
    menu             = 139,                 //  Menu (show menu)
    calc             = 140,                 //  AL Calculator
    setup            = 141,
    sleep            = 142,                 //  SC System Sleep
    wakeup           = 143,                 //  System Wake Up
    file             = 144,                 //  AL Local Machine Browser
    sendfile         = 145,
    deletefile       = 146,
    xfer             = 147,
    prog1            = 148,
    prog2            = 149,
    www              = 150,                 //  AL Internet Browser
    msdos            = 151,
    coffee           = 152,                 //  AL Terminal Lock/Screensaver
    rotate_display   = 153,                 //  Display orientation for e.g. tablets
    cyclewindows     = 154,
    mail             = 155,
    bookmarks        = 156,                 //  AC Bookmarks
    computer         = 157,
    back             = 158,                 //  AC Back
    forward          = 159,                 //  AC Forward
    closecd          = 160,
    ejectcd          = 161,
    ejectclosecd     = 162,
    nextsong         = 163,
    playpause        = 164,
    previoussong     = 165,
    stopcd           = 166,
    record           = 167,
    rewind           = 168,
    phone            = 169,                 //  Media Select Telephone
    iso              = 170,
    config           = 171,                 //  AL Consumer Control Configuration
    homepage         = 172,                 //  AC Home
    refresh          = 173,                 //  AC Refresh
    exit             = 174,                 //  AC Exit
    move             = 175,
    edit             = 176,
    scrollup         = 177,
    scrolldown       = 178,
    kpleftparen      = 179,
    kprightparen     = 180,
    new              = 181,                 //  AC New
    redo             = 182,                 //  AC Redo/Repeat
    f13              = 183,
    f14              = 184,
    f15              = 185,
    f16              = 186,
    f17              = 187,
    f18              = 188,
    f19              = 189,
    f20              = 190,
    f21              = 191,
    f22              = 192,
    f23              = 193,
    f24              = 194,
    playcd           = 200,
    pausecd          = 201,
    prog3            = 202,
    prog4            = 203,
    all_applications = 204,                 //  AC Desktop Show All Applications
    key_suspend      = 205,
    close            = 206,                 //  AC Close
    play             = 207,
    fastforward      = 208,
    bassboost        = 209,
    print            = 210,                 //  AC Print
    hp               = 211,
    camera           = 212,
    sound            = 213,
    question         = 214,
    email            = 215,
    chat             = 216,
    search           = 217,
    connect          = 218,
    finance          = 219,                 //  AL Checkbook/Finance
    sport            = 220,
    shop             = 221,
    alterase         = 222,
    cancel           = 223,                 //  AC Cancel
    brightnessdown   = 224,
    brightnessup     = 225,
    media            = 226,
    switchvideomode  = 227,                 //  Cycle between available video outputs (Monitor/LCD/TV-out/etc)
    kbdillumtoggle   = 228,
    kbdillumdown     = 229,
    kbdillumup       = 230,
    send             = 231,                 //  AC Send
    reply            = 232,                 //  AC Reply
    forwardmail      = 233,                 //  AC Forward Msg
    save             = 234,                 //  AC Save
    documents        = 235,
    battery          = 236,
    bluetooth        = 237,
    wlan             = 238,
    uwb              = 239,
    unknown          = 240,
    video_next       = 241,                 //  drive next video source
    video_prev       = 242,                 //  drive previous video source
    brightness_cycle = 243,                 //  brightness up, after max is min
    brightness_auto  = 244,                 //  Set Auto Brightness: manual brightness control is off, rely on ambient
    display_off      = 245,                 //  display device to off state
    wwan             = 246,                 //  Wireless WAN (LTE, UMTS, GSM, etc.)
    rfkill           = 247,                 //  Key that controls all radios
    micmute          = 248,                 //  Mute / unmute the microphone
    _,
    // zig fmt: on

    // Aliases
    pub const hanguel = Key.hangeul;
    pub const screenlock = Key.coffee;
    pub const direction = Key.rotate_display;
    pub const dashboard = Key.all_applications;
    pub const brightness_zero = Key.brightness_auto;
    pub const wimax = Key.wwan;

    pub fn to_int(self: Key) u8 {
        return @intFromEnum(self);
    }
};

pub fn deinit(_: *Self) void {}

fn x11_keycode_to_linux_key(keycode: x11.KeyCode) Key {
    std.debug.assert(keycode.to_int() >= 8);
    return @enumFromInt(keycode.to_int() - 8);
}

fn linux_key_to_x11_keycode(key: Key) x11.KeyCode {
    std.debug.assert(key.to_int() <= 248);
    return @enumFromInt(key.to_int() + 8);
}

pub fn get_min_keycode(_: *Self) x11.KeyCode {
    return @enumFromInt(8);
}

pub fn get_max_keycode(_: *Self) x11.KeyCode {
    return @enumFromInt(255);
}

// TODO: Read keyboard configuration from /usr/share/X11/xkb instead of manual mapping.
// The current mapping is for US keyboards.
pub fn x11_keycode_to_keysym(_: *const Self, keycode: x11.KeyCode) phx.KeySym {
    return switch (x11_keycode_to_linux_key(keycode)) {
        .reserved => phx.KeySyms.XKB_KEY_NoSymbol,
        .esc => phx.KeySyms.XKB_KEY_Escape,
        .num1 => phx.KeySyms.XKB_KEY_1,
        .num2 => phx.KeySyms.XKB_KEY_2,
        .num3 => phx.KeySyms.XKB_KEY_3,
        .num4 => phx.KeySyms.XKB_KEY_4,
        .num5 => phx.KeySyms.XKB_KEY_5,
        .num6 => phx.KeySyms.XKB_KEY_6,
        .num7 => phx.KeySyms.XKB_KEY_7,
        .num8 => phx.KeySyms.XKB_KEY_8,
        .num9 => phx.KeySyms.XKB_KEY_9,
        .num0 => phx.KeySyms.XKB_KEY_0,
        .minus => phx.KeySyms.XKB_KEY_minus,
        .equal => phx.KeySyms.XKB_KEY_equal,
        .backspace => phx.KeySyms.XKB_KEY_BackSpace,
        .tab => phx.KeySyms.XKB_KEY_Tab,
        .q => phx.KeySyms.XKB_KEY_q,
        .w => phx.KeySyms.XKB_KEY_w,
        .e => phx.KeySyms.XKB_KEY_e,
        .r => phx.KeySyms.XKB_KEY_r,
        .t => phx.KeySyms.XKB_KEY_t,
        .y => phx.KeySyms.XKB_KEY_y,
        .u => phx.KeySyms.XKB_KEY_u,
        .i => phx.KeySyms.XKB_KEY_i,
        .o => phx.KeySyms.XKB_KEY_o,
        .p => phx.KeySyms.XKB_KEY_p,
        .leftbrace => phx.KeySyms.XKB_KEY_braceleft,
        .rightbrace => phx.KeySyms.XKB_KEY_braceright,
        .enter => phx.KeySyms.XKB_KEY_Return,
        .leftctrl => phx.KeySyms.XKB_KEY_Control_L,
        .a => phx.KeySyms.XKB_KEY_a,
        .s => phx.KeySyms.XKB_KEY_s,
        .d => phx.KeySyms.XKB_KEY_d,
        .f => phx.KeySyms.XKB_KEY_f,
        .g => phx.KeySyms.XKB_KEY_g,
        .h => phx.KeySyms.XKB_KEY_h,
        .j => phx.KeySyms.XKB_KEY_j,
        .k => phx.KeySyms.XKB_KEY_k,
        .l => phx.KeySyms.XKB_KEY_l,
        .semicolon => phx.KeySyms.XKB_KEY_semicolon,
        .apostrophe => phx.KeySyms.XKB_KEY_apostrophe,
        .grave => phx.KeySyms.XKB_KEY_grave,
        .leftshift => phx.KeySyms.XKB_KEY_Shift_L,
        .backslash => phx.KeySyms.XKB_KEY_backslash,
        .z => phx.KeySyms.XKB_KEY_z,
        .x => phx.KeySyms.XKB_KEY_x,
        .c => phx.KeySyms.XKB_KEY_c,
        .v => phx.KeySyms.XKB_KEY_v,
        .b => phx.KeySyms.XKB_KEY_b,
        .n => phx.KeySyms.XKB_KEY_n,
        .m => phx.KeySyms.XKB_KEY_m,
        .comma => phx.KeySyms.XKB_KEY_comma,
        .dot => phx.KeySyms.XKB_KEY_period,
        .slash => phx.KeySyms.XKB_KEY_slash,
        .rightshift => phx.KeySyms.XKB_KEY_Shift_R,
        .kpasterisk => phx.KeySyms.XKB_KEY_asterisk,
        .leftalt => phx.KeySyms.XKB_KEY_Alt_L,
        .space => phx.KeySyms.XKB_KEY_space,
        .capslock => phx.KeySyms.XKB_KEY_Caps_Lock,
        .f1 => phx.KeySyms.XKB_KEY_F1,
        .f2 => phx.KeySyms.XKB_KEY_F2,
        .f3 => phx.KeySyms.XKB_KEY_F3,
        .f4 => phx.KeySyms.XKB_KEY_F4,
        .f5 => phx.KeySyms.XKB_KEY_F5,
        .f6 => phx.KeySyms.XKB_KEY_F6,
        .f7 => phx.KeySyms.XKB_KEY_F7,
        .f8 => phx.KeySyms.XKB_KEY_F8,
        .f9 => phx.KeySyms.XKB_KEY_F9,
        .f10 => phx.KeySyms.XKB_KEY_F10,
        .numlock => phx.KeySyms.XKB_KEY_Num_Lock,
        .scrolllock => phx.KeySyms.XKB_KEY_Scroll_Lock,
        .kp7 => phx.KeySyms.XKB_KEY_KP_7,
        .kp8 => phx.KeySyms.XKB_KEY_KP_8,
        .kp9 => phx.KeySyms.XKB_KEY_KP_9,
        .kpminus => phx.KeySyms.XKB_KEY_KP_Subtract,
        .kp4 => phx.KeySyms.XKB_KEY_KP_4,
        .kp5 => phx.KeySyms.XKB_KEY_KP_5,
        .kp6 => phx.KeySyms.XKB_KEY_KP_6,
        .kpplus => phx.KeySyms.XKB_KEY_KP_Add,
        .kp1 => phx.KeySyms.XKB_KEY_KP_1,
        .kp2 => phx.KeySyms.XKB_KEY_KP_2,
        .kp3 => phx.KeySyms.XKB_KEY_KP_3,
        .kp0 => phx.KeySyms.XKB_KEY_KP_0,
        .kpdot => phx.KeySyms.XKB_KEY_KP_Separator,
        .zenkakuhankaku => phx.KeySyms.XKB_KEY_Zenkaku_Hankaku,
        .key_102nd => phx.KeySyms.XKB_KEY_bar,
        .f11 => phx.KeySyms.XKB_KEY_F11,
        .f12 => phx.KeySyms.XKB_KEY_F12,
        .ro => phx.KeySyms.XKB_KEY_Romaji,
        .katakana => phx.KeySyms.XKB_KEY_Katakana,
        .hiragana => phx.KeySyms.XKB_KEY_Hiragana,
        .henkan => phx.KeySyms.XKB_KEY_Henkan,
        .katakanahiragana => phx.KeySyms.XKB_KEY_Hiragana_Katakana,
        .muhenkan => phx.KeySyms.XKB_KEY_Muhenkan,
        .kpjpcomma => phx.KeySyms.XKB_KEY_kana_comma,
        .kpenter => phx.KeySyms.XKB_KEY_KP_Enter,
        .rightctrl => phx.KeySyms.XKB_KEY_Control_R,
        .kpslash => phx.KeySyms.XKB_KEY_KP_Divide,
        .sysrq => phx.KeySyms.XKB_KEY_Sys_Req,
        .rightalt => phx.KeySyms.XKB_KEY_Alt_R,
        .linefeed => phx.KeySyms.XKB_KEY_Linefeed,
        .home => phx.KeySyms.XKB_KEY_Home,
        .up => phx.KeySyms.XKB_KEY_Up,
        .pageup => phx.KeySyms.XKB_KEY_Page_Up,
        .left => phx.KeySyms.XKB_KEY_Left,
        .right => phx.KeySyms.XKB_KEY_Right,
        .end => phx.KeySyms.XKB_KEY_End,
        .down => phx.KeySyms.XKB_KEY_Down,
        .pagedown => phx.KeySyms.XKB_KEY_Page_Down,
        .insert => phx.KeySyms.XKB_KEY_Insert,
        .delete => phx.KeySyms.XKB_KEY_Delete,
        .macro => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: Is this the correct key?
        .mute => phx.KeySyms.XKB_KEY_XF86AudioMute,
        .volumedown => phx.KeySyms.XKB_KEY_XF86AudioLowerVolume,
        .volumeup => phx.KeySyms.XKB_KEY_XF86AudioRaiseVolume,
        .power => phx.KeySyms.XKB_KEY_XF86PowerDown, // TODO: Is this the correct key?
        .kpequal => phx.KeySyms.XKB_KEY_KP_Equal,
        .kpplusminus => phx.KeySyms.XKB_KEY_plusminus, // TODO: Is this the correct key?
        .pause => phx.KeySyms.XKB_KEY_Pause,
        .scale => phx.KeySyms.XKB_KEY_XF86TaskPane, // TODO: Is this the correct key?
        .kpcomma => phx.KeySyms.XKB_KEY_KP_Separator,
        .hangeul => phx.KeySyms.XKB_KEY_Hangul,
        .hanja => phx.KeySyms.XKB_KEY_Hangul_Hanja,
        .yen => phx.KeySyms.XKB_KEY_yen,
        .leftmeta => phx.KeySyms.XKB_KEY_Meta_L,
        .rightmeta => phx.KeySyms.XKB_KEY_Meta_R,
        .compose => phx.KeySyms.XKB_KEY_SunCompose,
        .stop => phx.KeySyms.XKB_KEY_SunStop,
        .again => phx.KeySyms.XKB_KEY_SunAgain,
        .props => phx.KeySyms.XKB_KEY_SunProps,
        .undo => phx.KeySyms.XKB_KEY_SunUndo,
        .front => phx.KeySyms.XKB_KEY_SunFront, // TODO: Which key is this?
        .copy => phx.KeySyms.XKB_KEY_SunCopy, // TODO: Is this correct? or should it be XK_3270_Copy
        .open => phx.KeySyms.XKB_KEY_SunOpen,
        .paste => phx.KeySyms.XKB_KEY_SunPaste,
        .find => phx.KeySyms.XKB_KEY_SunFind,
        .cut => phx.KeySyms.XKB_KEY_SunCut,
        .help => phx.KeySyms.XKB_KEY_Help,
        .menu => phx.KeySyms.XKB_KEY_Menu,
        .calc => phx.KeySyms.XKB_KEY_XF86Calculator, // TODO: Is this the correct key?
        .setup => phx.KeySyms.XKB_KEY_3270_Setup, // TODO: Is this the correct key?
        .sleep => phx.KeySyms.XKB_KEY_XF86Sleep,
        .wakeup => phx.KeySyms.XKB_KEY_XF86WakeUp,
        .file => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: Which key is this?
        .sendfile => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: Which key is this?
        .deletefile => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: Which key is this?
        .xfer => phx.KeySyms.XKB_KEY_XF86Xfer,
        .prog1 => phx.KeySyms.XKB_KEY_XF86Launch1,
        .prog2 => phx.KeySyms.XKB_KEY_XF86Launch2,
        .www => phx.KeySyms.XKB_KEY_XF86WWW,
        .msdos => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: Which key is this?
        .coffee => phx.KeySyms.XKB_KEY_XF86Screensaver,
        .rotate_display => phx.KeySyms.XKB_KEY_XF86RotateWindows, // TODO: Is this correct?
        .cyclewindows => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: Which key is this?
        .mail => phx.KeySyms.XKB_KEY_XF86Mail,
        .bookmarks => phx.KeySyms.XKB_KEY_XF86Favorites,
        .computer => phx.KeySyms.XKB_KEY_XF86MyComputer,
        .back => phx.KeySyms.XKB_KEY_XF86Back,
        .forward => phx.KeySyms.XKB_KEY_XF86Forward,
        .closecd => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .ejectcd => phx.KeySyms.XKB_KEY_XF86Eject,
        .ejectclosecd => phx.KeySyms.XKB_KEY_XF86Eject,
        .nextsong => phx.KeySyms.XKB_KEY_XF86AudioNext,
        .playpause => phx.KeySyms.XKB_KEY_XF86MediaPlayPause,
        .previoussong => phx.KeySyms.XKB_KEY_XF86AudioPrev,
        .stopcd => phx.KeySyms.XKB_KEY_XF86Stop,
        .record => phx.KeySyms.XKB_KEY_XF86AudioRecord,
        .rewind => phx.KeySyms.XKB_KEY_XF86AudioRewind,
        .phone => phx.KeySyms.XKB_KEY_XF86Phone,
        .iso => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .config => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .homepage => phx.KeySyms.XKB_KEY_XF86HomePage,
        .refresh => phx.KeySyms.XKB_KEY_XF86Refresh,
        .exit => phx.KeySyms.XKB_KEY_XF86Exit,
        .move => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .edit => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .scrollup => phx.KeySyms.XKB_KEY_XF86ScrollUp,
        .scrolldown => phx.KeySyms.XKB_KEY_XF86ScrollDown,
        .kpleftparen => phx.KeySyms.XKB_KEY_parenleft,
        .kprightparen => phx.KeySyms.XKB_KEY_parenright,
        .new => phx.KeySyms.XKB_KEY_XF86New,
        .redo => phx.KeySyms.XKB_KEY_Redo,
        .f13 => phx.KeySyms.XKB_KEY_F13,
        .f14 => phx.KeySyms.XKB_KEY_F14,
        .f15 => phx.KeySyms.XKB_KEY_F15,
        .f16 => phx.KeySyms.XKB_KEY_F16,
        .f17 => phx.KeySyms.XKB_KEY_F17,
        .f18 => phx.KeySyms.XKB_KEY_F18,
        .f19 => phx.KeySyms.XKB_KEY_F19,
        .f20 => phx.KeySyms.XKB_KEY_F20,
        .f21 => phx.KeySyms.XKB_KEY_F21,
        .f22 => phx.KeySyms.XKB_KEY_F22,
        .f23 => phx.KeySyms.XKB_KEY_F23,
        .f24 => phx.KeySyms.XKB_KEY_F24,
        .playcd => phx.KeySyms.XKB_KEY_XF86AudioPlay,
        .pausecd => phx.KeySyms.XKB_KEY_XF86AudioPause,
        .prog3 => phx.KeySyms.XKB_KEY_XF86Launch3,
        .prog4 => phx.KeySyms.XKB_KEY_XF86Launch4,
        .all_applications => phx.KeySyms.XKB_KEY_XF86LaunchB,
        .key_suspend => phx.KeySyms.XKB_KEY_XF86Suspend,
        .close => phx.KeySyms.XKB_KEY_XF86Close,
        .play => phx.KeySyms.XKB_KEY_XF86AudioPlay,
        .fastforward => phx.KeySyms.XKB_KEY_XF86AudioForward,
        .bassboost => phx.KeySyms.XKB_KEY_XF86AudioBassBoost,
        .print => phx.KeySyms.XKB_KEY_Print,
        .hp => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .camera => phx.KeySyms.XKB_KEY_XF86WebCam,
        .sound => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .question => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .email => phx.KeySyms.XKB_KEY_XF86Mail,
        .chat => phx.KeySyms.XKB_KEY_XF86Messenger,
        .search => phx.KeySyms.XKB_KEY_XF86Search,
        .connect => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .finance => phx.KeySyms.XKB_KEY_XF86Finance,
        .sport => phx.KeySyms.XKB_KEY_XF86Sport,
        .shop => phx.KeySyms.XKB_KEY_XF86Shop,
        .alterase => phx.KeySyms.XKB_KEY_NoSymbol, // TODO: X11 doesn't support this key
        .cancel => phx.KeySyms.XKB_KEY_Cancel,
        .brightnessdown => phx.KeySyms.XKB_KEY_XF86MonBrightnessDown,
        .brightnessup => phx.KeySyms.XKB_KEY_XF86MonBrightnessUp,
        .media => phx.KeySyms.XKB_KEY_XF86AudioMedia,
        .switchvideomode => phx.KeySyms.XKB_KEY_XF86Display,
        .kbdillumtoggle => phx.KeySyms.XKB_KEY_XF86KbdLightOnOff,
        .kbdillumdown => phx.KeySyms.XKB_KEY_XF86KbdBrightnessDown,
        .kbdillumup => phx.KeySyms.XKB_KEY_XF86KbdBrightnessUp,
        .send => phx.KeySyms.XKB_KEY_XF86Send,
        .reply => phx.KeySyms.XKB_KEY_XF86Reply,
        .forwardmail => phx.KeySyms.XKB_KEY_XF86MailForward,
        .save => phx.KeySyms.XKB_KEY_XF86Save,
        .documents => phx.KeySyms.XKB_KEY_XF86Documents,
        .battery => phx.KeySyms.XKB_KEY_XF86Battery,
        .bluetooth => phx.KeySyms.XKB_KEY_XF86Bluetooth,
        .wlan => phx.KeySyms.XKB_KEY_XF86WLAN,
        .uwb => phx.KeySyms.XKB_KEY_XF86UWB,
        .unknown => phx.KeySyms.XKB_KEY_NoSymbol,
        .video_next => phx.KeySyms.XKB_KEY_XF86Next_VMode,
        .video_prev => phx.KeySyms.XKB_KEY_XF86Prev_VMode,
        .brightness_cycle => phx.KeySyms.XKB_KEY_XF86MonBrightnessCycle,
        .brightness_auto => phx.KeySyms.XKB_KEY_XF86MonBrightnessAuto,
        .display_off => phx.KeySyms.XKB_KEY_XF86DisplayOff,
        .wwan => phx.KeySyms.XKB_KEY_XF86WWAN,
        .rfkill => phx.KeySyms.XKB_KEY_XF86RFKill,
        .micmute => phx.KeySyms.XKB_KEY_XF86AudioMicMute,
        else => phx.KeySyms.XKB_KEY_NoSymbol,
    };
}

pub fn x11_modifier_keysym_to_x11_keycode(_: *Self, comptime keysym: phx.KeySym) x11.KeyCode {
    return comptime switch (keysym) {
        phx.KeySyms.XKB_KEY_Shift_L => linux_key_to_x11_keycode(.leftshift),
        phx.KeySyms.XKB_KEY_Shift_R => linux_key_to_x11_keycode(.rightshift),
        phx.KeySyms.XKB_KEY_Caps_Lock => linux_key_to_x11_keycode(.capslock),
        phx.KeySyms.XKB_KEY_Control_L => linux_key_to_x11_keycode(.leftctrl),
        phx.KeySyms.XKB_KEY_Control_R => linux_key_to_x11_keycode(.rightctrl),
        phx.KeySyms.XKB_KEY_Alt_L => linux_key_to_x11_keycode(.leftalt),
        phx.KeySyms.XKB_KEY_Alt_R => linux_key_to_x11_keycode(.rightalt),
        phx.KeySyms.XKB_KEY_Num_Lock => linux_key_to_x11_keycode(.numlock),
        phx.KeySyms.XKB_KEY_Meta_L => linux_key_to_x11_keycode(.leftmeta),
        phx.KeySyms.XKB_KEY_Meta_R => linux_key_to_x11_keycode(.rightmeta),
        phx.KeySyms.XKB_KEY_ISO_Level3_Shift => linux_key_to_x11_keycode(.rightalt),
        else => unreachable,
    };
}
